"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useQuotes, type Quote } from "../src/storage";

type View = "today"|"archive"|"add"|"queue"|"more";
const PEOPLE=["Frasier","Niles","Martin","Daphne","Roz","Eddie","Lilith","Bulldog","Bebe","Gil","Noel","Kenny","Donny","Mel","Frederick","Sherry","Ronee"];
if(typeof window!=="undefined" && !window.crypto.randomUUID){Object.defineProperty(window.crypto,"randomUUID",{value:()=>`q-${Date.now()}-${Math.random().toString(36).slice(2)}`})}
const KNOWN:Record<string,string>={"1-1":"The Good Son","1-24":"My Coffee with Niles","2-3":"The Matchmaker","3-17":"High Crane Drifter","4-1":"The Two Mrs. Cranes","5-14":"The Ski Lodge","6-17":"Dinner Party","7-15":"Out with Dad","8-9":"Frasier's Edge","9-14":"Juvenilia","10-14":"Daphne Does Dinner","11-24":"Goodnight, Seattle"};
function formatBody(body:string){return body.trim().split(/\n\s*\n/).filter(Boolean).map(part=>{const text=part.trim();if(text.startsWith("“")&&text.endsWith("”"))return text;return "“"+text.replace(/^[“\"]+|[”\"]+$/g,"")+"”"}).join("\n\n")}
function attribution(q:Quote){const names=q.speakers.length<2?q.speakers[0]:q.speakers.slice(0,-1).join(", ")+" and "+q.speakers.at(-1);return `- ${names}, S${q.season}E${q.episode}`}
function format(q:Quote){return `${formatBody(q.body)}\n\n${attribution(q)}`}

export default function Home(){
 const {quotes,save,ready,syncStatus,syncNow}=useQuotes(); const [view,setView]=useState<View>("today"); const [query,setQuery]=useState(""); const [copied,setCopied]=useState<string>(); const [online,setOnline]=useState(navigator.onLine); const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{const f=()=>setOnline(navigator.onLine);addEventListener("online",f);addEventListener("offline",f);return()=>{removeEventListener("online",f);removeEventListener("offline",f)}},[]);
 const queued=quotes.filter(q=>q.queued&&!q.postedAt); const today=queued[0]||quotes.find(q=>!q.postedAt); const suggested=quotes.find(q=>!q.postedAt&&q.id!==today?.id&&!q.queued);
 const mutate=(id:string,patch:Partial<Quote>)=>save(quotes.map(q=>q.id===id?{...q,...patch}:q));
 const copy=async(q:Quote)=>{await navigator.clipboard.writeText(format(q));setCopied(q.id);setTimeout(()=>setCopied(undefined),1800)};
 const add=(q:Quote)=>{save([q,...quotes]);setView(q.queued?"queue":"archive")};
 const exportData=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({schemaVersion:1,exportedAt:new Date().toISOString(),quotes},null,2)],{type:"application/json"}));a.download="frasier-quote-archive.json";a.click()};
 const importData=async(f:File)=>{try{const data=JSON.parse(await f.text());if(Array.isArray(data.quotes))save(data.quotes);alert("Archive restored.")}catch{alert("That file could not be imported.")}};
 return <div className="app-shell">
  <aside className="rail"><Brand/><nav><Nav view={view} setView={setView}/></nav><button className="rail-foot" onClick={syncNow}><span className={online?"dot":"dot off"}/>{online?syncStatus:"Offline ready"}</button></aside>
  <main className="main">
   <header className="mobile-head"><Brand/><button className="sync" onClick={syncNow} aria-label="Sync now"><span className={online?"dot":"dot off"}/>{online?syncStatus:"Offline"}</button></header>
   {!ready?<div className="loading">Tuning KACL…</div>:view==="today"?<Today q={today} suggestion={suggested} copy={copy} copied={copied} mutate={mutate} onEdit={()=>setView("add")}/>:view==="archive"?<Archive quotes={quotes} query={query} setQuery={setQuery} copy={copy} copied={copied} mutate={mutate}/>:view==="add"?<AddQuote onAdd={add}/>:view==="queue"?<Queue quotes={queued} mutate={mutate} copy={copy} copied={copied}/>:<More count={quotes.length} exportData={exportData} fileRef={fileRef} importData={importData}/>} 
  </main><nav className="bottom"><Nav view={view} setView={setView}/></nav>
 </div>
}

function Brand(){return <div className="brand"><div className="mic">●</div><div><span>KACL 780</span><strong>Frasier Archive</strong></div><b>ON AIR</b></div>}
const navs:[View,string,string][]=[["today","Today","◉"],["archive","Archive","⌕"],["add","Add","＋"],["queue","Queue","≡"],["more","More","•••"]];
function Nav({view,setView}:{view:View,setView:(v:View)=>void}){return <>{navs.map(([v,l,i])=><button key={v} className={`${view===v?"active":""} ${v==="add"?"add-nav":""}`} onClick={()=>setView(v)}><i>{i}</i><span>{l}</span></button>)}</>}
function Header({eyebrow,title,sub}:{eyebrow:string,title:string,sub:string}){return <div className="page-head"><div><p>{eyebrow}</p><h1>{title}</h1><span>{sub}</span></div><div className="wave">▂▅▃▆▂▇▃▅▂▆</div></div>}
function QuoteCard({q,copy,copied,mutate,hero=false}:{q:Quote;copy:(q:Quote)=>void;copied?:string;mutate:(id:string,p:Partial<Quote>)=>void;hero?:boolean}){return <article className={hero?"quote-card hero":"quote-card"}><div className="card-top"><span className="ep">S{q.season} · EP {q.episode}</span><button className={q.favorite?"star on":"star"} onClick={()=>mutate(q.id,{favorite:!q.favorite})} aria-label="Favorite">★</button></div><blockquote>{formatBody(q.body)}</blockquote><div className="attribution"><strong>{q.speakers.join(" & ")}</strong><span>{q.title||"Episode title"}</span></div><div className="actions"><button className="primary" onClick={()=>copy(q)}>{copied===q.id?"Copied ✓":"Copy for X"}</button>{!q.postedAt?<button onClick={()=>mutate(q.id,{postedAt:new Date().toISOString(),queued:false})}>Mark posted</button>:<span className="posted">Posted {new Date(q.postedAt).toLocaleDateString()}</span>}</div></article>}
function Today({q,suggestion,copy,copied,mutate,onEdit}:{q?:Quote;suggestion?:Quote;copy:(q:Quote)=>void;copied?:string;mutate:(id:string,p:Partial<Quote>)=>void;onEdit:()=>void}){return <section><Header eyebrow="Monday’s broadcast" title="Good afternoon, Seattle." sub="Your next quote is ready for air."/>{q?<QuoteCard q={q} copy={copy} copied={copied} mutate={mutate} hero/>:<Empty text="Your archive is waiting for its first quote."/>}<div className="last-line"><span>Last posted</span><strong>4 days ago</strong><span>· Niles · S6 Ep17</span></div>{suggestion&&<div className="suggestion"><div><p>ALTERNATE TAKE</p><h2>Maybe this one instead?</h2></div><p>“{suggestion.body.slice(0,105)}”</p><div><button onClick={()=>mutate(suggestion.id,{queued:true})}>Add to queue</button><button onClick={onEdit}>Edit quote</button></div></div>}</section>}
function Archive({quotes,query,setQuery,copy,copied,mutate}:{quotes:Quote[];query:string;setQuery:(s:string)=>void;copy:(q:Quote)=>void;copied?:string;mutate:(id:string,p:Partial<Quote>)=>void}){const [filter,setFilter]=useState("all");const list=useMemo(()=>quotes.filter(q=>{const text=(q.body+q.speakers.join(" ")+q.title+` s${q.season} ep${q.episode}`).toLowerCase();return text.includes(query.toLowerCase())&&(filter==="all"||filter==="favorites"&&q.favorite||filter==="unposted"&&!q.postedAt||filter==="queued"&&q.queued)}),[quotes,query,filter]);return <section><Header eyebrow={`${quotes.length} saved quotations`} title="The Archive" sub="Every bon mot, barb and beautiful disaster."/><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search quote, character or episode…"/></div><div className="chips">{["all","unposted","favorites","queued"].map(x=><button className={filter===x?"on":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div><div className="results"><p>{list.length} {list.length===1?"result":"results"} · Recently added</p>{list.map(q=><QuoteCard key={q.id} q={q} copy={copy} copied={copied} mutate={mutate}/>)}</div></section>}
function AddQuote({onAdd}:{onAdd:(q:Quote)=>void}){const [body,setBody]=useState("");const [speakers,setSpeakers]=useState<string[]>(["Frasier"]);const [season,setSeason]=useState(3);const [episode,setEpisode]=useState(17);const [notes,setNotes]=useState("");const q:Quote={id:crypto.randomUUID(),body,speakers,season,episode,title:KNOWN[`${season}-${episode}`]||"",favorite:false,queued:false,notes,createdAt:new Date().toISOString()};const submit=(queued:boolean)=>body.trim()&&onAdd({...q,queued});return <section><Header eyebrow="Studio notebook" title="Capture a quote" sub="From memory to archive in under thirty seconds."/><div className="form-card"><label>QUOTE OR EXCHANGE<textarea autoFocus value={body} onChange={e=>setBody(e.target.value)} placeholder={'Type each spoken line, with a blank line between speakers.\n\nQuotation marks are added automatically.'}/><small>{format(q).length} copied characters</small></label><fieldset><legend>SPEAKERS</legend><div className="people">{PEOPLE.map(p=><button type="button" className={speakers.includes(p)?"chosen":""} onClick={()=>setSpeakers(speakers.includes(p)?speakers.filter(x=>x!==p):[...speakers,p])} key={p}>{p}</button>)}</div></fieldset><div className="row"><label>SEASON<select value={season} onChange={e=>setSeason(+e.target.value)}>{Array.from({length:11},(_,i)=><option key={i}> {i+1}</option>)}</select></label><label>EPISODE<select value={episode} onChange={e=>setEpisode(+e.target.value)}>{Array.from({length:24},(_,i)=><option key={i}>{i+1}</option>)}</select></label></div><label>PRIVATE NOTES<input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Optional context, tags or reminder"/></label><div className="preview"><span>X PREVIEW · {format(q).length}/280</span><p>{body?formatBody(body):"Your quote preview will appear here."}</p>{body&&<strong>{attribution(q)}</strong>}</div><div className="save-row"><button onClick={()=>submit(false)}>Save quote</button><button className="primary" onClick={()=>submit(true)}>Save & queue</button></div></div></section>}
function Queue({quotes,mutate,copy,copied}:{quotes:Quote[];mutate:(id:string,p:Partial<Quote>)=>void;copy:(q:Quote)=>void;copied?:string}){return <section><Header eyebrow={`${quotes.length} days prepared`} title="The Queue" sub="Your upcoming broadcasts, in order."/>{quotes.length?<div className="queue-list">{quotes.map((q,i)=><div className="queue-row" key={q.id}><b>{String(i+1).padStart(2,"0")}</b><div><span>{q.speakers.join(" & ")} · S{q.season} Ep{q.episode}</span><p>{q.body}</p></div><button onClick={()=>copy(q)}>{copied===q.id?"✓":"Copy"}</button><button onClick={()=>mutate(q.id,{queued:false})}>×</button></div>)}</div>:<Empty text="Nothing queued yet. Add a quote when inspiration strikes."/>}</section>}
function More({count,exportData,fileRef,importData}:{count:number;exportData:()=>void;fileRef:React.RefObject<HTMLInputElement|null>;importData:(f:File)=>void}){return <section><Header eyebrow="Control room" title="More" sub="Backup, restore and fine-tune your archive."/><div className="settings"><div><span>ARCHIVE HEALTH</span><h2>{count} quotes safely stored</h2><p>Available offline on this device. Cloud synchronization resumes automatically.</p></div><button onClick={exportData}><b>↓</b><span><strong>Export backup</strong><small>Download a complete JSON archive</small></span></button><button onClick={()=>fileRef.current?.click()}><b>↑</b><span><strong>Restore backup</strong><small>Import a Frasier Archive JSON file</small></span></button><input ref={fileRef} hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&importData(e.target.files[0])}/><div><span>ABOUT</span><p>Original 1993–2004 series · Personal archive for Cydney · No login required</p></div></div></section>}
function Empty({text}:{text:string}){return <div className="empty"><b>◉</b><h2>Dead air.</h2><p>{text}</p></div>}
