import type {Quote} from './storage';
import {episodeFor} from './data/episodes';
export type ArchiveFilters={characters:string[];seasons:number[];episodes:string[];postingStatus:'any'|'posted'|'unposted';queueStatus:'any'|'queued'|'notQueued';favoritesOnly:boolean;hasNotes:boolean;quoteType:'any'|'single'|'exchange'};
export type ArchiveSort='recent'|'oldest'|'episode'|'episodeReverse'|'recentlyPosted'|'character';
export const EMPTY_FILTERS:ArchiveFilters={characters:[],seasons:[],episodes:[],postingStatus:'any',queueStatus:'any',favoritesOnly:false,hasNotes:false,quoteType:'any'};
export function normalizeSearch(value:string){return value.normalize('NFKD').replace(/\p{M}/gu,'').replace(/[’‘'`´]/g,'').replace(/&/g,' and ').replace(/[^a-z0-9]+/gi,' ').trim().toLowerCase().replace(/\s+/g,' ')}
export function formatBody(body:string){return body.trim().split(/\n\s*\n/).filter(Boolean).map(part=>{const text=part.trim();if(text.startsWith('“')&&text.endsWith('”'))return text;return '“'+text.replace(/^[“\"]+|[”\"]+$/g,'')+'”'}).join('\n\n')}
export function episodeTitle(q:Quote){return episodeFor(q.season,q.episode)?.title||q.title||''}
export function matchesSearch(q:Quote,query:string){const terms=normalizeSearch(query).split(' ').filter(Boolean);if(!terms.length)return true;const episode=`s${q.season}e${q.episode} s${q.season} ep${q.episode} season ${q.season} episode ${q.episode}`;const haystack=normalizeSearch([q.body,q.speakers.join(' and '),episodeTitle(q),episode,q.notes||''].join(' '));return terms.every(term=>haystack.includes(term))}
export function matchesFilters(q:Quote,f:ArchiveFilters){if(f.characters.length&&!f.characters.some(x=>q.speakers.includes(x)))return false;if(f.seasons.length&&!f.seasons.includes(q.season))return false;if(f.episodes.length&&!f.episodes.includes(`${q.season}-${q.episode}`))return false;if(f.postingStatus==='posted'&&!q.postedAt)return false;if(f.postingStatus==='unposted'&&q.postedAt)return false;if(f.queueStatus==='queued'&&!q.queued)return false;if(f.queueStatus==='notQueued'&&q.queued)return false;if(f.favoritesOnly&&!q.favorite)return false;if(f.hasNotes&&!q.notes?.trim())return false;if(f.quoteType==='single'&&q.speakers.length!==1)return false;if(f.quoteType==='exchange'&&q.speakers.length<2)return false;return true}
export function sortQuotes(items:Quote[],sort:ArchiveSort){return [...items].sort((a,b)=>{let n=0;if(sort==='recent')n=b.createdAt.localeCompare(a.createdAt);if(sort==='oldest')n=a.createdAt.localeCompare(b.createdAt);if(sort==='episode'||sort==='episodeReverse')n=(a.season-b.season)||(a.episode-b.episode);if(sort==='episodeReverse')n=-n;if(sort==='recentlyPosted')n=(b.postedAt||'').localeCompare(a.postedAt||'');if(sort==='character')n=(a.speakers[0]||'').localeCompare(b.speakers[0]||'');return n||a.id.localeCompare(b.id)})}
export function activeFilterCount(f:ArchiveFilters){return f.characters.length+f.seasons.length+f.episodes.length+(f.postingStatus==='any'?0:1)+(f.queueStatus==='any'?0:1)+(f.favoritesOnly?1:0)+(f.hasNotes?1:0)+(f.quoteType==='any'?0:1)}
