import Dexie,{type EntityTable}from'dexie';import{useCallback,useEffect,useState}from'react';
export type Quote={id:string;body:string;speakers:string[];season:number;episode:number;title:string;favorite:boolean;queued:boolean;postedAt?:string;notes?:string;createdAt:string;updatedAt?:string;deletedAt?:string;revision?:number;deviceId?:string};
type OutboxItem=Quote&{queuedAt:string};const db=new Dexie('frasier-archive')as Dexie&{quotes:EntityTable<Quote,'id'>;outbox:EntityTable<OutboxItem,'id'>};db.version(3).stores({quotes:'id,createdAt,updatedAt,season,episode,queued,favorite,deletedAt',outbox:'id,queuedAt'});
const deviceId=(()=>{const e=localStorage.getItem('frasier-device-id');if(e)return e;const n=crypto.randomUUID();localStorage.setItem('frasier-device-id',n);return n})();
function fromServer(r:Record<string,unknown>):Quote{return{id:String(r.id),body:String(r.body),speakers:Array.isArray(r.speakers)?r.speakers.map(String):JSON.parse(String(r.speakers||'[]')),season:Number(r.season),episode:Number(r.episode),title:String(r.title||''),favorite:Boolean(r.favorite),queued:Boolean(r.queued),postedAt:r.postedAt?String(r.postedAt):r.posted_at?String(r.posted_at):undefined,notes:r.notes?String(r.notes):undefined,createdAt:String(r.createdAt||r.created_at),updatedAt:String(r.updatedAt||r.updated_at||''),deletedAt:r.deletedAt?String(r.deletedAt):r.deleted_at?String(r.deleted_at):undefined,revision:Number(r.revision||1),deviceId:r.deviceId?String(r.deviceId):r.device_id?String(r.device_id):undefined}}
export function useQuotes(){const[quotes,setQuotes]=useState<Quote[]>([]),[ready,setReady]=useState(false),[syncStatus,setSyncStatus]=useState('Synced');
const syncNow=useCallback(async()=>{if(!navigator.onLine){setSyncStatus('Offline ready');return}setSyncStatus('Syncing…');try{const pending=await db.outbox.toArray();if(pending.length){const response=await fetch('/api/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({changes:pending})});if(!response.ok)throw new Error();const result=await response.json()as{accepted:string[]};await db.outbox.bulkDelete(result.accepted)}const response=await fetch('/api/bootstrap',{cache:'no-store'});if(!response.ok)throw new Error();const payload=await response.json()as{quotes:Record<string,unknown>[]};const remote=payload.quotes.map(fromServer),waiting=new Set((await db.outbox.toArray()).map(x=>x.id)),local=await db.quotes.toArray(),merged=new Map(remote.map(q=>[q.id,q]));local.forEach(q=>{if(waiting.has(q.id)||!merged.has(q.id))merged.set(q.id,q)});const next=[...merged.values()].sort((a,b)=>b.createdAt.localeCompare(a.createdAt));await db.quotes.bulkPut(next);setQuotes(next);setSyncStatus('Synced')}catch{const waiting=await db.outbox.count();setSyncStatus(waiting?`${waiting} waiting`:'Sync problem')}},[]);
useEffect(()=>{let active=true;void(async()=>{const local=await db.quotes.orderBy('createdAt').reverse().toArray();if(active){setQuotes(local);setReady(true)}await syncNow();if(navigator.storage?.persist)void navigator.storage.persist()})();const online=()=>void syncNow(),visible=()=>{if(document.visibilityState==='visible')void syncNow()};addEventListener('online',online);document.addEventListener('visibilitychange',visible);return()=>{active=false;removeEventListener('online',online);document.removeEventListener('visibilitychange',visible)}},[syncNow]);
const write=useCallback(async(q:Quote)=>{const now=new Date().toISOString(),next={...q,updatedAt:now,revision:(q.revision||0)+1,deviceId},out={...next,queuedAt:now};await db.transaction('rw',db.quotes,db.outbox,async()=>{await db.quotes.put(next);await db.outbox.put(out)});setQuotes(await db.quotes.orderBy('createdAt').reverse().toArray());void syncNow()},[syncNow]);
const createQuote=useCallback((q:Quote)=>write(q),[write]);const updateQuote=useCallback(async(id:string,patch:Partial<Quote>)=>{const q=await db.quotes.get(id);if(q)await write({...q,...patch,id:q.id,createdAt:q.createdAt})},[write]);const deleteQuote=useCallback((id:string)=>updateQuote(id,{deletedAt:new Date().toISOString()}),[updateQuote]);const restoreQuote=useCallback((id:string)=>updateQuote(id,{deletedAt:undefined}),[updateQuote]);
const replaceArchive=useCallback(async(next:Quote[])=>{const now=new Date().toISOString(),normalized=next.map(q=>({...q,updatedAt:now,revision:(q.revision||0)+1,deviceId}));await db.transaction('rw',db.quotes,db.outbox,async()=>{await db.quotes.clear();await db.quotes.bulkPut(normalized);await db.outbox.bulkPut(normalized.map(q=>({...q,queuedAt:now})))});setQuotes(normalized);void syncNow()},[syncNow]);return{quotes,ready,syncStatus,syncNow,createQuote,updateQuote,deleteQuote,restoreQuote,replaceArchive}}
